name: Deploy to EC2 Instance
# Only trigger deploy when the pylint/pytest is successful.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  pylint:
    uses: ./.github/workflows/pylint.yml
  pytest:
    uses: ./.github/workflows/pytest.yml
  job3:
    needs: [pylint,pytest] 
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to EC2
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
