name: Deploy to Staging Server
# Only trigger when the pylint/pytest is successful.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  job1:
    uses: ./.github/workflows/pylint.yml
  job2:
    uses: ./.github/workflows/pytest.yml
  job3:
    runs-on: ubuntu-latest
    needs: [job1,job2]      
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}